### ISSUE TITLE
Readme is incorrect for OktaAuthStateService

### ISSUE THREAD

**Issue by Kilowhisky** [okta/okta-angular#104]
### Describe the bug?

https://github.com/okta/okta-angular#oktaauthstateservice

At this URL it appears that the component references a service that was not imported in the constructor. 

The service also provided does not contain the methods mentioned in the documentation. 

### What is expected to happen?

nothing

### What is the actual behavior?

readme incorrect. 

### Reproduction Steps?

its treadme

### SDK Versions

latest

### Execution Environment

readme.

**Comment by denysoblohin-okta** [comment]
Readme issue has been fixed in https://github.com/okta/okta-angular/pull/90
