### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading '_oktaUserAgent')

### ISSUE THREAD

**Issue by gkumardminc** [okta/okta-angular#109]
### Describe the bug?

Hi Team, followed the documentation, but hard to say that butld is failing with the result of below error:
**TypeError: Cannot read properties of undefined (reading '_oktaUserAgent')**

Document I followed:
[https://www.npmjs.com/package/@okta/okta-angular](https://www.npmjs.com/package/@okta/okta-angular)

Angular version: **14.2.6**
NodeJs: **16**

Code: **app.module.ts**
Imports:

```
**import {OktaAuthModule, OKTA_CONFIG } from '@okta/okta-angular';
import {OktaAuth} from '@okta/okta-auth-js';**

import { LoginComponent } from './login/login.component';
import { HomeComponent } from './home/home.component';
import { LogoutComponent } from './logout/logout.component';


  const oktaConfig = {
    clientId: '0oa6vkir35UqFCkvS5d7',
    issuer: 'https://dev-67505432.okta.com/oauth2/default',
    redirectUri: 'http://localhost:4200/login/callback',
    
    //scopes: ['openid', 'profile', 'email'],
    // responseType: ['code'] as OAuthResponseType | OAuthResponseType[],
    // pkce: false,
    // tokenManager: {
    //   expireEarlySeconds: 290,
    //   autoRenew: true
    // },
    // onSessionExpired: () => {
    //   console.log('User session expired. Redirect to login page');
    //   authClient.tokenManager.clear();
    //   authClient.token.getWithRedirect();
    // }
  };


providers: [
    { 
      provide: OKTA_CONFIG, 
      useValue: { authClient } 
    }
  ]
```

As soon as we execute this code with ng serve or npm start, it throws error in console.

Please help me on this, this is ruining my life. Please please help me.

[okta-demo-login.zip](https://github.com/okta/okta-angular/files/9798851/okta-demo-login.zip)

Thanks, and Regards
Gautam

### What is expected to happen?

We should get poup or okta login page.

### What is the actual behavior?

Throws an error, TypeError: Cannot read properties of undefined (reading '_oktaUserAgent')

### Reproduction Steps?

1. Create new angular folder with version 14=+.
2. Add the import and add config 
3. Run the application

### SDK Versions

@okta/okta-angular
TypeScript icon, indicating that this package has built-in type declarations
6.0.0

### Execution Environment

Angular 14.0+

**Comment by denysoblohin-okta** [comment]
Try to rename `authClient` to `oktaAuth` :

```js

providers: [
    { 
      provide: OKTA_CONFIG, 
      useValue: { oktaAuth } 
    }
  ]
```

**Comment by gkumardminc** [comment]
Ya thank you so much.. it worked, what a silly mistake i did.. 👌😀

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
