### ISSUE TITLE
Cannot run Jest tests with okta-angular 6.0.0

### ISSUE THREAD

**Issue by abaran30** [okta/okta-angular#110]
### Describe the bug?

After upgrading to okta-angular 6.0.0, although applications with Okta auth continue to work, unit tests via Jest (with jest-preset-angular) fail to run.

### What is expected to happen?

Unit tests via Jest continue to run and pass.

### What is the actual behavior?

Unit tests fail to run with the following error:

```
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/adbaran/Development/GitHub/adbaran1/nx-playground/node_modules/@okta/okta-angular/fesm2015/okta-angular.js:12
    import { __awaiter } from 'tslib';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { Component, Inject, OnInit } from '@angular/core';
    > 2 | import { OKTA_AUTH } from '@okta/okta-angular';
        | ^
      3 | import OktaAuth from '@okta/okta-auth-js';
```

### Reproduction Steps?

1. Clone https://github.com/adbaran1/nx-playground
2. `git checkout chore/okta-6-jest` (project is set up only to reproduce the test issue)
3. `npm ci`
4. Attempt to run tests for my-app with `npx nx run my-app:test`

### SDK Versions

@okta/okta-angular: 6.0.0
@okta/okta-auth-js: 7.0.1

Nx version 15.0.13
Angular version ~14.2.0
Jest version 28.1.3

### Execution Environment

Node version 18.12.0
npm version 8.19.2
OS version macOS Monterey (12.5.1)

**Comment by adbaran1** [comment]
One workaround for this is to add `@okta/okta-angular` to `transformIgnorePatterns` in the project Jest config:
```ts
export default {
  ...
  transformIgnorePatterns: ['node_modules/(?!.*.mjs$|@okta/okta-angular)'],
  ...
}
```
However, we're wondering if an official solution/adaptation can be applied.

**Comment by jaredperreault-okta** [comment]
Thanks for the report, we will investigate this

Internal Ref: OKTA-551971

**Comment by denysoblohin-okta** [comment]
@abaran30

**Comment by denysoblohin-okta** [comment]
@abaran30 
 https://github.com/adbaran1/nx-playground returns 404

Can you post your jest config please?

I am able to run Jest tests with the following config (using `jest-preset-angular`):
```js
// jest.config.js
export default {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  transformIgnorePatterns: [
  ],
};
```
```js
// setup-jest.ts
import 'jest-preset-angular/setup-jest';
```

**Comment by denysoblohin-okta** [comment]
@abaran30 Next major version of okta-angular will include using `.mjs` extension instead of `.js` which will resolve issue with Jest. 
But for now please add `@okta/okta-angular` to `transformIgnorePatterns` in jest config

**Comment by MO2k4** [comment]
> @abaran30 Next major version of okta-angular will include using `.mjs` extension instead of `.js` which will resolve issue with Jest. But for now please add `@okta/okta-angular` to `transformIgnorePatterns` in jest config

@denysoblohin-okta any eta for this?
