### ISSUE TITLE
Supporting angular version 15

### ISSUE THREAD

**Issue by kaluginserg** [okta/okta-angular#113]
### Describe the feature request?

The new version of angular is released (https://blog.angular.io/angular-v15-is-now-available-df7be7f2f4c8 ).

Problem: Projects that have already been updated to the new version of Angular can't use the current version of the library.

Currently, in the description of the library, we have such text:
``` This library has been tested for compatibility with the following Angular versions: 7, 8, 9, 10, 11, 12, 13, 14 ```.

So, we need to update this library (or check compatibility and reflect it in the documentation) to support the new Angular version.

### New or Affected Resource(s)

-

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @kaluginserg. Documentation will be updated.
Internal Ref: OKTA-553002

**Comment by denysoblohin-okta** [comment]
Documentation has been updated. Test app for Angular 15 has been added.
