### ISSUE TITLE
Token renewal reloads entire app.

### ISSUE THREAD

**Issue by jraadt** [okta/okta-angular#12]
In the 2.x to 3.x migration doc under the `"Active" token renew` section it says `Now, tokens will be renewed in the background before they expire.`. I took that to mean _silently_ in the background. But 30 seconds before my current token is set to expire, it reloads my whole app, potentially losing data the user has not submitted yet, not to mention an undesirable user experience. When it does the token renewal I'm still signed into Okta so it just reloads the app and sets the new tokens. I don't have to actually sign in again.

Is there a recommended approach to doing this silently in the background with the new version 3 of okta-angular? With the typical token expiration of 1 hour it means everyone's apps will continue to hard reload every hour.

**Comment by jraadt** [comment]
My browser settings were blocking 3rd party cookies in Incognito mode (which I use for testing auth). I now see that the `okta-auth-js` docs say:

> Many browsers have started blocking cross-origin or "third party" cookies by default. Although most of the Okta APIs supported by this SDK do not rely upon cookies, there are a few methods which do.

The auto renew code in Okta calls `token.getWithoutPrompt` which is one of those methods. Once I enable all cookies for incognito mode, everything renews silently in the background. The docs also say:

> Okta engineers are currently working on a better long-term solution to this problem.

I would love to know more about how the engineers are tackling that problem and the progress.

**Comment by aarongranick-okta** [comment]
@jraadt We are a developing a solution which enables "offline_access" scope and refresh tokens for SPA applications as currently exists for Web/Native app types. This solution should be available by the end of the year.

**Comment by jraadt** [comment]
That's great @aarongranick-okta ! I'm looking forward to trying that out. Appreciate all the hard work.

**Comment by dali07** [comment]
Hello everyone,
Any news on this issue?
We are in 2023 and it seems that the same problem persists with incognito mode.

**Comment by jaredperreault-okta** [comment]
@dali07 Can you please create a new issue and include all relevant package versions and repro steps? Thank you
