### ISSUE TITLE
Update project to Angular 16: Infite refresh app after login.

### ISSUE THREAD

**Issue by robuandrei** [okta/okta-angular#129]
### Describe the bug

After I've updated my project to the latest version of Angular (16.1.2) from version 15.
When I've performed the authentication the application enters an infinite refresh loop and I receive this warning message in the browser console:
**[okta-auth-sdk] WARN: a saved auth transaction exists in storage. This may indicate another auth flow is already in progress.**

With version 15 of Angular, everything works fine.

### Reproduction Steps?

1. Update to the latest version of the Angular framework.
2. Run the project locally or deploy in some environment (it doesn't matter).
3. The app enters an infinite refresh loop.

### SDK Versions

    "@angular/animations": "16.1.2",
    "@angular/common": "16.1.2",
    "@angular/compiler": "16.1.2",
    "@angular/core": "16.1.2",
    "@angular/forms": "16.1.2",
    "@angular/platform-browser": "16.1.2",
    "@angular/platform-browser-dynamic": "16.1.2",
    "@angular-devkit/build-angular": "^16.1.1",
    "@angular-eslint/builder": "16.0.3",
    "@angular-eslint/eslint-plugin": "16.0.3",
    "@angular-eslint/eslint-plugin-template": "16.0.3",
    "@angular-eslint/schematics": "16.0.3",
    "@angular-eslint/template-parser": "16.0.3",
    "@angular/cdk": "^16.1.1",
    "@angular/cli": "^16.1.1",
    "@angular/compiler-cli": "^16.1.1",

    "@okta/okta-angular": "6.2.0",
    "@okta/okta-auth-js": "7.3.0",

### Additional Information

In my factory !authOkta.authStateManager.getPreviousAuthState()?.isAuthenticated, every time is true.

**Comment by shuowu-okta** [comment]
Thanks for reporting the issue! 

Internal Ref: OKTA-627451

**Comment by jaredperreault-okta** [comment]
@robuandrei Are you able to make a sample repo that illustrates this issue? I added an angular 16 test app and I was able to login in both manually and it passed our e2e tests

**Comment by robuandrei** [comment]
Hi @jaredperreault-okta. I've managed to fix it.
The issue was on the routing module of the app.
On the 16 version of Angular if the root path is used without a component the app enters an infinite loop.
This is the wrong code:
![image](https://github.com/okta/okta-angular/assets/10831964/8095843d-c06f-4d51-8847-c08c4ef56774)
The problem is fixed with the following:
![image](https://github.com/okta/okta-angular/assets/10831964/dde43f5d-c43e-42f2-a76d-44b38b30c2a4)

So I think the bug can be closed from now, because is fixed.
