### ISSUE TITLE
Are you able to provide a pure JavaScript example to get username? 

### ISSUE THREAD

**Issue by monitorjain** [okta/okta-angular#13]
Hi Okta Team,

Is there a possible way to access okta username or email via pure javascript (instead of JS frameworks like Angular? Your help with this is highly appreciated.

Best
Nik Jain

**Comment by aarongranick-okta** [comment]
@monitorjain We have a pure javascript SDK, https://github.com/okta/okta-auth-js/ Our Angular SDK is built on top of this.

The okta-auth-js SDK has some samples as well: https://github.com/okta/okta-auth-js/tree/master/samples

To receive username and email, you should add "profile" and "email" to the list of scopes. These values will be properties of the "claims" object on the ID token.

**Comment by alsoicode** [comment]
@monitorjain Here's a TypeScript example, but hopefully it will be enough to demonstrate. Depending on the claims you're sending in, you might need to access different keys:

```
    const storageData: object = JSON.parse(this.window.localStorage.getItem('okta-token-storage'));
    const idToken = 'idToken';
    let claimsData: IClaims = null;

    if (storageData?.[idToken]?.claims) {
      const claims: IClaims = storageData[idToken].claims;

      claimsData = {
        Hyper_firstName: claims.Hyper_firstName || '',
        Hyper_lastName: claims.Hyper_lastName || '',
      };
    }
```

**Comment by shuowu** [comment]
You can also use the [getUser](https://github.com/okta/okta-auth-js#getuser) api from okta-auth-js.
