### ISSUE TITLE
Fails to install on M1 BigSur MacOS install....

### ISSUE THREAD

**Issue by thenetimp** [okta/okta-angular#23]
% npm install okta/okta-angular
npm ERR! prepareGitDep 1>
npm ERR! prepareGitDep > fsevents@1.2.13 install /Users/username/.npm/_cacache/tmp/git-clone-86571535/node_modules/fsevents
npm ERR! prepareGitDep > node install.js
npm ERR! prepareGitDep
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/.node
npm ERR! prepareGitDep   CXX(target) Release/obj.target/fse/fsevents.o
npm ERR! prepareGitDep   SOLINK_MODULE(target) Release/fse.node
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@3.8.3 postinstall /Users/username/.npm/_cacache/tmp/git-clone-86571535/node_modules/@okta/okta-auth-js/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@2.6.12 postinstall /Users/username/.npm/_cacache/tmp/git-clone-86571535/node_modules/babel-polyfill/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@2.6.12 postinstall /Users/username/.npm/_cacache/tmp/git-clone-86571535/node_modules/babel-runtime/node_modules/core-js
npm ERR! prepareGitDep > node -e "try{require('./postinstall')}catch(e){}"
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > @compodoc/compodoc@1.1.9 postinstall /Users/username/.npm/_cacache/tmp/git-clone-86571535/node_modules/@compodoc/compodoc
npm ERR! prepareGitDep > opencollective postinstall
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep      *** Thank you for using @compodoc/compodoc! ***
npm ERR! prepareGitDep
npm ERR! prepareGitDep Please consider donating to our open collective
npm ERR! prepareGitDep      to help us maintain this package.
npm ERR! prepareGitDep
npm ERR! prepareGitDep   https://opencollective.com/compodoc/donate
npm ERR! prepareGitDep
npm ERR! prepareGitDep                     ***
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > core-js@3.1.3 postinstall /Users/username/.npm/_cacache/tmp/git-clone-86571535/node_modules/core-js
npm ERR! prepareGitDep > node scripts/postinstall || echo "ignore"
npm ERR! prepareGitDep
npm ERR! prepareGitDep Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
npm ERR! prepareGitDep
npm ERR! prepareGitDep The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
npm ERR! prepareGitDep > https://opencollective.com/core-js
npm ERR! prepareGitDep > https://www.patreon.com/zloirock
npm ERR! prepareGitDep
npm ERR! prepareGitDep Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep > @okta/okta-angular@3.1.0 prepare /Users/username/.npm/_cacache/tmp/git-clone-86571535
npm ERR! prepareGitDep > yarn build
npm ERR! prepareGitDep
npm ERR! prepareGitDep
npm ERR! prepareGitDep 2> npm WARN install Usage of the `--dev` option is deprecated. Use `--also=dev` instead.
npm ERR! prepareGitDep npm WARN deprecated tslint@6.1.3: TSLint has been deprecated in favor of ESLint. Please see https://github.com/palantir/tslint/issues/4534 for more information.
npm ERR! prepareGitDep npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm ERR! prepareGitDep npm WARN deprecated ts-simple-ast@12.4.0: NOTICE: ts-simple-ast has been renamed to ts-morph and version reset to 1.0.0. Switch at your leisure...
npm ERR! prepareGitDep npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm ERR! prepareGitDep npm WARN deprecated text-encoding@0.7.0: no longer maintained
npm ERR! prepareGitDep npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! prepareGitDep npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm ERR! prepareGitDep npm WARN deprecated opn@6.0.0: The package has been renamed to `open`
npm ERR! prepareGitDep npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! prepareGitDep npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! prepareGitDep npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! prepareGitDep npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm ERR! prepareGitDep npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm ERR! prepareGitDep sh: yarn: command not found
npm ERR! prepareGitDep npm ERR! code ELIFECYCLE
npm ERR! prepareGitDep npm ERR! syscall spawn
npm ERR! prepareGitDep npm ERR! file sh
npm ERR! prepareGitDep npm ERR! errno ENOENT
npm ERR! prepareGitDep npm ERR! @okta/okta-angular@3.1.0 prepare: `yarn build`
npm ERR! prepareGitDep npm ERR! spawn ENOENT
npm ERR! prepareGitDep npm ERR!
npm ERR! prepareGitDep npm ERR! Failed at the @okta/okta-angular@3.1.0 prepare script.
npm ERR! prepareGitDep npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! prepareGitDep
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /Users/username/.npm/_logs/2021-02-07T06_57_21_743Z-debug.log
npm ERR! prepareGitDep
npm ERR! premature close

**Comment by aarongranick-okta** [comment]
```
npm ERR! prepareGitDep sh: yarn: command not found
```
It appearas `okta-angular` requires `yarn` to be installed

**Comment by openbridge-james** [comment]
I hadn't noticed @aarongranick-okta's original response.   Seems kind of bad that you force a user to use one package manager vs another.  I don't have yarn on my machine cause I don't see any advantage over npm.  I certainly am not going to install it just to test out a possible solution.

**Comment by mraible** [comment]
Okta Angular doesn't require Yarn. It works just fine with npm. I just tried it yesterday. However, I'm on a MacBook Pro, not an M1.
