### ISSUE TITLE
StateToken, requestUri -> SignInWidget Bootstrapping

### ISSUE THREAD

**Issue by vladzz** [okta/okta-angular#25]
When we upgraded okta-angular to package greater then 2.2 bootstraping the signin widget via Statetoken and requestUri broke the callback to our application. Also the widget was asking for additional settings like clientId. The vanilla javascript lib doesn't require these when bootstrapping with stateToken and RequestUri and works as intended.

We are now unable to update our dependencies until this issue is fixed. Please look at fixing this ASAP.

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for reporting this. 

@swiftone / @shuowu-okta can you help here?

**Comment by swiftone** [comment]
@vladzz - Sorry to hear you're having troubles, however what you report hasn't been mentioned by others, so I suspect it can be corrected by configuration.

Have you followed the steps outlined in our Migration Guide?  ( https://github.com/okta/okta-angular/blob/master/MIGRATING.md#from-version-2x-to-3x )

**Comment by aarongranick-okta** [comment]
@vladzz It sounds like you are doing [a non-OIDC flow](https://github.com/okta/okta-signin-widget#non-oidc-applications). How are you acquiring a stateToken?

**Comment by swiftone** [comment]
@vladzz - is this the same issue you also reported on the signin-widget?  ( https://github.com/okta/okta-signin-widget/issues/1671 )

**Comment by vladzz** [comment]
Hi @swiftone it is the same issue.
