### ISSUE TITLE
getAccessToken/getIdToken return single character not a valid JWT

### ISSUE THREAD

**Issue by xmlking** [okta/okta-angular#34]
after SSO login with Okta I am 
`this.oktaAuth.getAccessToken()` is printed as ‘A’ and `IDToken` as ‘g’ , only a single character return. I expected valid JWT,  
The `this.oktaAuth.getUser()` call works fine

![image](https://user-images.githubusercontent.com/627951/114730456-bc990e80-9cf5-11eb-87aa-442798d54658.png)

more details here:
https://github.com/akveo/nebular/issues/2071#issuecomment-818864828

**Comment by xmlking** [comment]
this is how I am using 
https://github.com/xmlking/yeti/blob/develop/libs/core/src/lib/services/okta-auth.strategy.ts

**Comment by arvindkrishnakumar-okta** [comment]
Thanks for posting! 

@aarongranick-okta / @shuowu-okta can you help take a look?

**Comment by xmlking** [comment]
Tanks Okta team. you can reproduce the above issue by cloning `github.com:xmlking/yeti` and run `nx serve webapp` then cline 3rd Icon in `http://localhost:4200/home/login` to start SSO

**Comment by xmlking** [comment]
I also added google as an external IDP to enable the social login option, but I don't see login-with-google button 
![image](https://user-images.githubusercontent.com/627951/114803322-17f9e980-9d54-11eb-8d73-bf26c7dd63c0.png)

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for sharing the repro environment @xmlking.

It looks like token values are getting truncated by `forkJoin` statement - it returns only last emitted value(last character for the token strings).

> I also added google as an external IDP to enable the social login option, but I don't see login-with-google button

Can you please post the relevant part of your Okta-hosted SIW configuration and SIW version from the customization page?
Did you specify `idps` config option?
```
<script type="text/javascript">
  var config = OktaUtil.getSignInWidgetConfig();
  config.idps = [{ type: "google", id: "idpIdFromOktaAdminPanel" }];
  var oktaSignIn = new OktaSignIn(config);
  oktaSignIn.renderEl(
  ...
 ```

**Comment by xmlking** [comment]
I don't know what `Okta-hosted SIW configuration `  means. 
 I am using the free trial and I haven't setup  any customization page
![image](https://user-images.githubusercontent.com/627951/117083493-ae894d00-acf9-11eb-9dec-35da33651f45.png)

**Comment by oleksandrpravosudko-okta** [comment]
The sign in UI on your org's [page](https://dev-13501486.okta.com/) is referred to as Okta-hosted [sign-in widget](https://github.com/okta/okta-signin-widget).
It can be [customized](https://developer.okta.com/docs/guides/style-the-widget/style-okta-hosted/) through the admin [page](https://dev-13501486-admin.okta.com/admin/settings/customizableSignIn#tab-customizable-sign-in).

**Comment by oleksandrpravosudko-okta** [comment]
Going to close this issue. @xmlking feel free to re-open/open new issue in case sign-in flow doesn't work in expected way.
