### ISSUE TITLE
Custom login and password reset forms

### ISSUE THREAD

**Issue by jakehockey10** [okta/okta-angular#38]
This is just a question, not an issue with the library.  My company would like to use a 3rd party auth provider, like Okta, rather than storing the passwords in an encrypted fashion ourselves.  But my company would also like to have login and password reset UIs that are part of our angular application.  Is it possible to sign in/reset password with a custom form, and not using a redirect flow or an embedded widget?

Some examples online seem to show that this is possible, but looking through the public interface of this library, I don't see anything that makes this possible.  If it is possible, is it a matter of using the lower-level, non-angular okta javascript library?

**Comment by jakehockey10** [comment]
It looks like the Service class extends the `OktaAuth` object that has a `signInWithCredentials` method that seems to do what I want.  Also, there is a `forgotPassword` method on `OktaAuth`.  Is it possible to reset the password without SMS or Call involved?

**Comment by shuowu** [comment]
@jakehockey10 You found the right place, okta-angular depends on the core `okta-auth-js` SDK, which supports making calls to Okta's authn API for authentications and forgot password usage. You can explore [okta-auth-js API reference](https://github.com/okta/okta-auth-js#api-reference) for detail usages. 

References: 
[Authentication API](https://developer.okta.com/docs/reference/api/authn/)
[Authn status](https://github.com/okta/okta-auth-js#transactionstatus)
[Code sample](https://github.com/okta/okta-auth-js/blob/master/samples/generated/static-spa/public/app.js#L267)

**Comment by jakehockey10** [comment]
Upon further inspection, it does not look like forgotPassword allows you to perform the operation without a redirect.  Is this true?  There isn't a way for me to send a password change request, having the user provide their current password as well as their new password and new password confirmation?

**Comment by jakehockey10** [comment]
@shuowu  I would also like to know how to perform self-service registration with my own UI.  Is this possible?  I can't find any documentation in the API for the javascript library.

**Comment by shuowu** [comment]
@jakehockey10 Afaik, it's not supported in the client SDKs. You still can build it against the [Users API](https://github.com/okta/okta-angular/issues/38), or use our [node management sdk](https://github.com/okta/okta-sdk-nodejs).

**Comment by jakehockey10** [comment]
@shuowu thanks for the response. Just to make sure I'm looking at the right page, could you fix the users api link above?

**Comment by shuowu** [comment]
@jakehockey10 sorry, my bad... updated!

**Comment by shuowu** [comment]
@jakehockey10 Close the issue for now, feel free to reopen the issue if you have further question.
