### ISSUE TITLE
response type is not supported by the authorization server

### ISSUE THREAD

**Issue by dexyppdf** [okta/okta-angular#41]
I am getting "The response type is not supported by the authorization server. Configured response types id_token token ." after callback route. Please help me on this

**Comment by bryanapellanes-okta** [comment]
@dexyppdf,
Thanks for reaching out!  I'll bring this to the attention of our Javascript developers and someone will follow up with you here.

Thanks for using Okta!

**Comment by bryanapellanes-okta** [comment]
Internal Ref: OKTA-395687

**Comment by shuowu** [comment]
@dexyppdf Can you share your app's configuration? Here is config details per [responseType](https://github.com/okta/okta-auth-js#responsetype).

**Comment by oleksandrpravosudko-okta** [comment]
@dexyppdf do you have `Allow ID/Access Token with implicit grant type` enabled in your OIDC app configuration?

**Comment by oleksandrpravosudko-okta** [comment]
Closing this issue - @dexyppdf feel free to reopen in case it is still relevant.
