### ISSUE TITLE
autoRenew is no longer working in latest Angular SDK 3.2.0

### ISSUE THREAD

**Issue by martyngroberts** [okta/okta-angular#47]
autoRenew is no longer working in latest version of Okta Angular SDK 3.2.0 which references okta-auth-js 5.2.1.  

Steps to recreate;

1. unauthenticated user browses to Angular app
2. Browser redirects to Okta sign-in page
3. User logs in with username and password
4. ID token, access token and refresh token returned 
5. Access token lifetime set to 5 mins 
6. User waits 5 mins 
9. Network trace shows no new API calls to Okta in this time (eg. /token)
10. Access token expiry time passes (nothing happens in browser)
11. User must interact with app to refresh token

In previous version of SDK (3.1.0), the autoRenew is working

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for reporting this @martyngroberts - we will have this investigated and fixed.
Internal Ref: OKTA-411446

**Comment by oleksandrpravosudko-okta** [comment]
It looks like token expiration handler is not set during login redirect - https://github.com/okta/okta-angular/pull/48 (WIP) should address this issue.

**Comment by shuowu** [comment]
@martyngroberts The fix is release in version 3.2.1. Closing the issue, feel free to re-open it if the issue still exists.
