### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by kpeters-cbsi** [okta/okta-angular#55]
## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
in README.md there is a broken link to "@okta/okta-auth-jks" 

## Expected behavior
Link should be "@okta/okta-auth-js"

### Steps to reproduce: 
1. Read README.md 
2. Notice typo under `OktaAuthService`
3. ??
4. Profit!

## Extra information about the use case/user story you are trying to implement

N/A

## Environment
N/A

## Configuration
N/A

**Comment by aarongranick-okta** [comment]
internal ref: OKTA-418644
