### ISSUE TITLE
Could not find a declaration file for module @okta/okta-signin-widget

### ISSUE THREAD

**Issue by mpitsenberger** [okta/okta-angular#61]
## I'm submitting a:
- [X] Bug report: Could not find a declaration file for module @okta/okta-signin-widget

## Current behavior
We are unable to use the OKTA sign in widget in our angular application

## Expected behavior
The okta sign widget loads correctly in our angular application

## Minimal reproduction of the problem with instructions
[Sending Screen Shots]

## Extra information about the use case/user story you are trying to implement
[Sending Screen Shots]

## Environment

- Package version: 5.10.0
- Angular version: 12.0.0
- Browser: Chrome
- OS: Windows 
- Node version (`node -v`): 16.8.0
- Other: 

## Configuration
- Okta application type: OAUTH2.0
![OKTA Screen Shot 2](https://user-images.githubusercontent.com/90057383/132043172-b27dcd7e-16f4-4b8c-bf83-f3e44c05f134.png)
![OKTA Screen Shot 3](https://user-images.githubusercontent.com/90057383/132043173-609a7dae-36aa-4bde-bf35-9bace1321055.png)
![OKTA Screen Shot 1](https://user-images.githubusercontent.com/90057383/132043176-cbdde335-27b1-4630-882a-9e9a5743abd0.png)

**Comment by shuowu** [comment]
@mpitsenberger The current [@okta/okta-signin-widget](https://github.com/okta/okta-signin-widget) module is not providing types. Can you set a loose type rule to bypass the type errors?

**Comment by mpitsenberger** [comment]
Thanks we were able resolve the issue

**Comment by sislex** [comment]
how do you solve it?

**Comment by mraible** [comment]
Create a `src/typings.d.ts` file with the following:

```ts
declare module 'text-encoding';
declare module '@okta/okta-signin-widget';
```

https://github.com/okta-samples/okta-angular-sample/blob/main/src/typings.d.ts
