### ISSUE TITLE
Base href missing in 'referrerPath'

### ISSUE THREAD

**Issue by Kalmanto** [okta/okta-angular#7]
OktaAuthGuard uses RouterStateSnapshot.url as "fromUri" to call "setFromUri"

`this.oktaAuth.setFromUri(state.url);`

OktaAuthService uses "window.location.origin + fromUri" to set "referrerPath"

`      if (fromUri.charAt(0) === '/') {
        fromUri = window.location.origin + fromUri;
      }
      sessionStorage.setItem('referrerPath', fromUri);`

If my app is deployed under "https://www.example.com/dashboard/" and router path "" is protected by OktaAuthGuard, when I visit "https://www.example.com/dashboard/", OktaAuthGuard will use "/" as fromUri to call "setFromUri", then window.location.origin would be "https://www.example.com" and  "referrerPath" would be just "https://www.example.com/", the sub path "dashboard" is missing.

**Comment by aarongranick-okta** [comment]
@Kalmanto Thank you for the submission. We are aware of this issue and are working on a solution. In the meantime there is a workaround available described here: https://github.com/okta/okta-oidc-js/issues/745 Hopefully this will hep.

**Comment by swiftone** [comment]
Support for base href was added/fixed in okta-angular 3.0.1 - https://github.com/okta/okta-angular/releases/tag/okta-angular-3.0.1

Please let us know if this does not address your issue.
