### ISSUE TITLE
Okta angular can’t compile with “ng build –prod”

### ISSUE THREAD

**Issue by DavidAaronOrtiz** [okta/okta-angular#72]
## I'm submitting a:

- [X] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior
Running "ng build --prod" causes the following error:
ERROR in Can’t resolve all parameters for OktaAuthGuard in //node_modules/@okta/okta-angular/okta-angular.d.ts: ([object Object], ?, [object Object]).
Can’t resolve all parameters for OktaAuthStateService in //node_modules/@okta/okta-angular/okta-angular.d.ts: (?).
Can’t resolve all parameters for OktaCallbackComponent in //node_modules/@okta/okta-angular/okta-angular.d.ts: ([object Object], ?, [object Object]).
Can’t resolve all parameters for LoginPage in //src/app/pages/login/login.page.ts: ([object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], [object Object], ?).

## Expected behavior
Application will compile correctly

## Minimal reproduction of the problem with instructions
Run "ng build --prod" 

## Extra information about the use case/user story you are trying to implement
"ng serve" compiles. Already added skipLibCheck in the tsconfig.

## Environment

- Package version:
  "@okta/okta-angular": 4.1.0
  "@okta/okta-auth-js": 5.5.0
- Angular version: 8.2.14
- Browser: any
- OS: macOS Mojave 10.14.6
- Node version (`node -v`): 10.16.3
- Other:

## Configuration

- Okta application type: SPA

**Comment by oleksandrpravosudko-okta** [comment]
Thanks for report @DavidAaronOrtiz.
Internal Ref: OKTA-435165

**Comment by shuowu** [comment]
@DavidAaronOrtiz It's probably because of the typescript version from Angular 8 cannot compatible with types in the newly published version. Can you try upgrade the angular version or use older version of okta-angular as a workaround?

Also, here is our [angular samples repo](https://github.com/okta/samples-js-angular), I just verified the build script works well there.

**Comment by shuowu** [comment]
@DavidAaronOrtiz The issue should be fixed in [version 4.1.1](https://github.com/okta/okta-angular/releases/tag/okta-angular-4.1.1) 

Closing this issue, feel free to reopen it if the problem still exist.

**Comment by gvdmierop** [comment]
@shuowu 
I'm experiencing the following error running 'ng build --prod' using version 4.1.1 on an Angular 7 project.

Can’t resolve all parameters for OktaCallbackComponent in //node_modules/@okta/okta-angular/okta-angular.d.ts: ([object Object], ?, [object Object]).

It's also one of the errors mentioned by @DavidAaronOrtiz so I think this issue is not entirely fixed in version 4.1.1.

Can you look into this again, please?
In the meanwhile I'll try to downgrade the okta-angular version to get around this.

**Comment by yamanch123** [comment]
I am also getting the same error using version 4.1.1 on an Angular 8 project.

**Comment by yamanch123** [comment]
I am also getting the same error using version 4.1.1 on an Angular 8 project.
Can't resolve all parameters for OktaAuthGuard in //node_modules/@okta/okta-angular/okta-angular.d.ts: ([object Object], ?, [object Object]).

**Comment by gvdmierop** [comment]
> @shuowu I'm experiencing the following error running 'ng build --prod' using version 4.1.1 on an Angular 7 project.
> 
> Can’t resolve all parameters for OktaCallbackComponent in //node_modules/@okta/okta-angular/okta-angular.d.ts: ([object Object], ?, [object Object]).
> 
> It's also one of the errors mentioned by @DavidAaronOrtiz so I think this issue is not entirely fixed in version 4.1.1.
> 
> Can you look into this again, please? In the meanwhile I'll try to downgrade the okta-angular version to get around this.

Downgrading to 3.2.2 fixed it for now.

**Comment by gvdmierop** [comment]
> > @shuowu I'm experiencing the following error running 'ng build --prod' using version 4.1.1 on an Angular 7 project.
> > Can’t resolve all parameters for OktaCallbackComponent in //node_modules/@okta/okta-angular/okta-angular.d.ts: ([object Object], ?, [object Object]).
> > It's also one of the errors mentioned by @DavidAaronOrtiz so I think this issue is not entirely fixed in version 4.1.1.
> > Can you look into this again, please? In the meanwhile I'll try to downgrade the okta-angular version to get around this.
> 
> Downgrading to 3.2.2 fixed it for now.

Unfortunately, I had to downgrade to 2.1.0.
3.2.2 version was built succesfully, but at runtime it gave me the error 'Uncaught TypeError: Super expression must either be null or a function'

Still, I would like to use a more recent version, as version 2.1.0 does not work with refresh token mechanisms yet.

Any news on a possible fix for this?

Thank you.

**Comment by shuowu** [comment]
@gvdmierop @yamanch123 @DavidAaronOrtiz A fix PR is created [here](https://github.com/okta/okta-angular/pull/79), can you verify against that PR branch to see if the fix works? (The PR is a bit verbose, since we want to create test apps cross different versions to verify the code change.)

**Comment by gvdmierop** [comment]
@shuowu ,

The fix PR seems to be the solution for our Angular 7 app!
Note that I had to add `@Inject(OKTA_AUTH)` to every component where we inject an OktaAuth instance:


`@Inject(OKTA_AUTH) private oktaAuth: OktaAuth
`

On a sidenote, this issue made us aware that we should plan an upgrade to a more recent angular version better sooner than later. However our app is large and complex so this solution seems perfect for getting Okta integrated (including refresh token mechanisms) on a shorter term.

Any idea when this fix could be released?
Thank you!

**Comment by shuowu** [comment]
The fix went out in v5.0 since it introduces breaking change. Closing this issue, feel free to re-open if you are still seeing the issue in v5.
