### ISSUE TITLE
Uncaught In Promise Error in Console log but Redirect from Okta Login is working correctly

### ISSUE THREAD

**Issue by monasterx3** [okta/okta-angular#73]
## I'm submitting a:

- [x] Bug report  
- [ ] Feature request
- [ ] Other (Describe below)

## Current behavior

I am seeing the following error in console log after I log into Application. The redirect and implementation is working correctly but I would like to find a way to remove this error.

Okta Route Login: 
`  {
    path: 'login/callback',
    component: OktaCallbackComponent,
  },`
 
Implementation in App Component

`  ngOnInit() {
    this.oktaAuthService.authStateManager.subscribe((oktaState: IOktaState) => {
      this.consumeOktaState(oktaState);
    });
}`

SDK: @okta/okta-angular 3.2.2
Language: Angular

<img width="661" alt="Screen Shot 2021-10-20 at 3 03 15 PM" src="https://user-images.githubusercontent.com/38019200/138155797-6130f972-4bbf-48a3-b425-cc09cd66747c.png">

## Expected behavior

No error in console log

## Minimal reproduction of the problem with instructions

After Okta login redirects to Application, error appears in console.

## Environment

- Package version: 3.2.2
- Angular version: 12
- Browser: Chrome
- OS: macOS
- Node version (`node -v`): v12.22.1
- Other:

## Configuration

- Okta application type:

**Comment by monasterx3** [comment]
@mraible thank you for the quick response. I have the okta configs pointing to /login/callback 
`   redirectUri: 'http://localhost:4200/login/callback',`

**Comment by mraible** [comment]
@barbozaa Yes, your redirect in the Okta Admin Console have to match what you have in your app.

**Comment by barbozaa** [comment]
Thank you @mraible
