### ISSUE TITLE
Access token is not stored when using the Okta-Signin-Widget lib

### ISSUE THREAD

**Issue by ArkasDev** [okta/okta-angular#8]
I would like to implement the Okta custom login. I use the widget for authentication and it works fine. When I authenticate with the embedded widget, I also get the token. I can see the token in the network tab in the developer module, also I can see the user information directly after login. But as soon as I navigate to another page, either the access token is lost or it was never stored in the Angular application. I suppose that there is a problem with the callback on the @okta/okta-angular library. But if I use the example, the authentication works without problems: https://github.com/okta/samples-js-angular/tree/master/custom-login. I don't know what the problem is with the integration into my webapp. Any ideas?

![test](https://user-images.githubusercontent.com/16050090/98173803-059d9900-1ef4-11eb-829c-68486fe2d94e.png)

**widget**
```
@Component({
  selector: 'app-authentication',
  templateUrl: './authentication.component.html',
  styleUrls: ['./authentication.component.scss'],
})
export class AuthenticationComponent implements OnInit {
  public widget: any;
  public user: any;

   constructor() {
    this.widget = new OktaSignIn({
      baseUrl: 'https://dev.oktapreview.com',
      clientId: '',
      redirectUri: 'http://localhost:3000/implicit/callback'
    });
  }

  public ngOnInit(): void {
    this.widget.renderEl({ el: '#okta-login-container' }, (response: any) => { }
  }
```

**routing.module.ts**
```
export const ROUTES_WEB: Routes = [
{
  path: 'implicit/callback',
  component: OktaCallbackComponent
},
...
];

@NgModule({
  declarations: [],
  imports: [
    RouterModule.forRoot(ROUTES_WEB)
  ],
  exports: [RouterModule]
})
export class RootRoutingModule {}

```

**app.module.ts**
```
const oktaConfig = {
  issuer: 'https://dev.oktapreview.com/oauth2/default',
  redirectUri: 'http://localhost:3000/implicit/callback',
  clientId: '',
  scopes: ['openid', 'profile', 'email', 'groups'],
  pkce: true,
};

@NgModule({
  declarations: [AppComponent],
  imports: [BrowserModule, BrowserAnimationsModule, CoreModule, OktaAuthModule],
  providers: [{ provide: OKTA_CONFIG, useValue: oktaConfig }],
  bootstrap: [AppComponent],
  exports: [],
})
export class AppModule {}
```

**package.json**
```
"@okta/okta-angular": "^2.2.1",
"@okta/okta-signin-widget": "^5.0.0",
```

**tsconfig.json**
```
{
  "files": ["src/main.ts", "src/polyfills.ts"],
  "include": ["src/**/*.d.ts"],
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "module": "esnext",
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom"],
    "baseUrl": ".",
    "paths": {
      "@src/*": ["src/*.web.ts", "src/*.ts"]
    }
  }
}
```

**Comment by shuowu** [comment]
@ArkasDev We do suggest use `showSignInToGetTokens ` instead of `renderEl` to get tokens. Also, since version 5.0, the `showSignInToGetTokens` stops redirect, see details in [MIGRATING](https://github.com/okta/okta-signin-widget/blob/master/MIGRATING.md#migrating-from-4x-to-5x)

For storing the tokens, you will need to use the `oktaAuth` instance from `okta-angualr` to store tokens in the success callback.

```
this.oktaAuth.getTokenManager().add('accessToken', accessToken);
this.oktaAuth.getTokenManager().add('idToken', idToken);
```
